paths:
  uploads: uploads/public/images
  static: ''
collections_config:
  source:
    path: ''
    icon: package_2
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: pages
    icon: wysiwyg
    url: /[relative_path]
    disable_url: false
    include_developer_files: false
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  dashboard:
    path: dashboard
    icon: dashboard
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs:
    path: docs
    icon: docs
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Asia/Colombo
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
