backend:
  name: git-gateway
  branch: main

media_folder: "assets/images" # Images save aaga
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Hero Subtitle", name: "subtitle", widget: "string"}
  
  - name: "products"
    label: "Daraz Products"
    folder: "products" # Pudhu items inge save aagum
    create: true
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Price (With Profit)", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
